services:
  mysql:
    image: mysql
    container_name: final-capstone-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: hotels_management
      TZ: Asia/Ho_Chi_Minh
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql